improv in dynamic patition device

diff --git a/core/utils/kopi/META-INF/com/google/android/update-binary b/core/utils/kopi/META-INF/com/google/android/update-binary
--- a/core/utils/kopi/META-INF/com/google/android/update-binary
+++ b/core/utils/kopi/META-INF/com/google/android/update-binary
@@ -1,7 +1,7 @@
 #!/sbin/sh
 # Kopi Installer V1.5
 # Since 08-05-2020
-# Latest Update 20-09-2021
+# Latest Update 01-10-2021
 # by wahyu6070 (dont change)
 
 OUTFD=/proc/self/fd/$2;
@@ -155,69 +155,70 @@ setenforce 0
 [ "$ANDROID_ROOT" ] || ANDROID_ROOT=/system;
 
 
-file_getprop() { $BB grep "^$2=" "$1" | $BB cut -d= -f2-; }
+file_getprop() { grep "^$2=" "$1" | cut -d= -f2-; }
 find_slot() {
   local slot=$(getprop ro.boot.slot_suffix 2>/dev/null);
-  [ "$slot" ] || slot=$($BB grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline | $BB cut -d\  -f1 | $BB cut -d= -f2);
+  [ "$slot" ] || slot=$(grep -o 'androidboot.slot_suffix=.*$' /proc/cmdline | cut -d\  -f1 | cut -d= -f2);
   if [ ! "$slot" ]; then
     slot=$(getprop ro.boot.slot 2>/dev/null);
-    [ "$slot" ] || slot=$($BB grep -o 'androidboot.slot=.*$' /proc/cmdline | $BB cut -d\  -f1 | $BB cut -d= -f2);
+    [ "$slot" ] || slot=$(grep -o 'androidboot.slot=.*$' /proc/cmdline | cut -d\  -f1 | cut -d= -f2);
     [ "$slot" ] && slot=_$slot;
   fi;
   [ "$slot" ] && echo "$slot";
 }
 setup_mountpoint() {
-  [ -L $1 ] && $BB mv -f $1 ${1}_link;
+  [ -L $1 ] && mv -f $1 ${1}_link;
   if [ ! -d $1 ]; then
-    $BB rm -f $1;
-    $BB mkdir -p $1;
+    rm -f $1;
+    mkdir -p $1;
   fi;
 }
-is_mounted() { $BB mount | $BB grep -q " $1 "; }
+is_mounted() { mount | grep -q " $1 "; }
 mount_apex() {
   [ -d /system_root/system/apex ] || return 1;
   local apex dest loop minorx num var;
   setup_mountpoint /apex;
   minorx=1;
-  [ -e /dev/block/loop1 ] && minorx=$($BB ls -l /dev/block/loop1 | $BB awk '{ print $6 }');
+  [ -e /dev/block/loop1 ] && minorx=$(ls -l /dev/block/loop1 | awk '{ print $6 }');
   num=0;
   for apex in /system_root/system/apex/*; do
-    dest=/apex/$($BB basename $apex .apex);
+    dest=/apex/$(basename $apex .apex);
     case $dest in
-      *.current|*.release) dest=$(echo $dest | $BB rev | $BB cut -d. -f2- | $BB rev);;
+      *.current|*.release) dest=$(echo $dest | rev | cut -d. -f2- | rev);;
     esac;
-    $BB mkdir -p $dest;
+    mkdir -p $dest;
+    print "- Mounting $dest"
     case $apex in
       *.apex)
-        $BB unzip -qo $apex apex_payload.img -d /apex;
-        $BB mv -f /apex/apex_payload.img $dest.img;
-        $BB mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
+        unzip -qo $apex apex_payload.img -d /apex;
+        mv -f /apex/apex_payload.img $dest.img;
+        mount -t ext4 -o ro,noatime $dest.img $dest 2>/dev/null;
         if [ $? != 0 ]; then
           while [ $num -lt 64 ]; do
             loop=/dev/block/loop$num;
-            ($BB mknod $loop b 7 $((num * minorx));
-            $BB losetup $loop $dest.img) 2>/dev/null;
+            (mknod $loop b 7 $((num * minorx));
+            losetup $loop $dest.img) 2>/dev/null;
             num=$((num + 1));
-            $BB losetup $loop | $BB grep -q $dest.img && break;
+            losetup $loop | grep -q $dest.img && break;
           done;
-          $BB mount -t ext4 -o ro,loop,noatime $loop $dest;
+          mount -t ext4 -o ro,loop,noatime $loop $dest;
           if [ $? != 0 ]; then
-            $BB losetup -d $loop 2>/dev/null;
+            losetup -d $loop 2>/dev/null;
           fi;
         fi;
       ;;
-      *) $BB mount -o bind $apex $dest;;
+      *) mount -o bind $apex $dest;;
     esac;
   done;
-  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB awk '{ print $2 }'); do
+  for var in $(grep -o 'export .* /.*' /system_root/init.environ.rc | awk '{ print $2 }'); do
     eval OLD_${var}=\$$var;
   done;
-  $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB sed 's; /;=/;'); unset export;
+  $(grep -o 'export .* /.*' /system_root/init.environ.rc | sed 's; /;=/;'); unset export;
 }
 umount_apex() {
   [ -d /apex/com.android.runtime ] || return 1;
   local dest loop var;
-  for var in $($BB grep -o 'export .* /.*' /system_root/init.environ.rc | $BB awk '{ print $2 }'); do
+  for var in $(grep -o 'export .* /.*' /system_root/init.environ.rc | awk '{ print $2 }'); do
     if [ "$(eval echo \$OLD_$var)" ]; then
       eval $var=\$OLD_${var};
     else
@@ -225,100 +226,107 @@ umount_apex() {
     fi;
     unset OLD_${var};
   done;
-  for dest in $($BB find /apex -type d -mindepth 1 -maxdepth 1); do
+  for dest in $(find /apex -type d -mindepth 1 -maxdepth 1); do
     if [ -f $dest.img ]; then
-      loop=$($BB mount | $BB grep $dest | $BB cut -d\  -f1);
+      loop=$(mount | grep $dest | cut -d\  -f1);
     fi;
-    ($BB umount -l $dest;
-    $BB losetup -d $loop) 2>/dev/null;
+    (umount -l $dest;
+    losetup -d $loop) 2>/dev/null;
   done;
-  $BB rm -rf /apex 2>/dev/null;
+  rm -rf /apex 2>/dev/null;
 }
 mount_all() {
-  local byname mount slot system;
   if ! is_mounted /cache; then
-    $BB mount /cache 2>/dev/null && UMOUNT_CACHE=1;
+     mount /cache 2>/dev/null && UMOUNT_CACHE=1;
   fi;
   if ! is_mounted /data; then
-    $BB mount /data && UMOUNT_DATA=1;
+     mount /data && UMOUNT_DATA=1;
   fi;
-  (for mount in /vendor /product /system_ext /persist; do
-    $BB mount -o ro -t auto $mount;
-  done) 2>/dev/null;
+  ( mount -o ro -t auto /vendor;
+   mount -o ro -t auto /product;
+   mount -o ro -t auto /persist) 2>/dev/null;
   setup_mountpoint $ANDROID_ROOT;
   if ! is_mounted $ANDROID_ROOT; then
-    $BB mount -o ro -t auto $ANDROID_ROOT 2>/dev/null;
+     mount -o ro -t auto $ANDROID_ROOT 2>/dev/null;
   fi;
-  byname=bootdevice/by-name;
-  [ -d /dev/block/$byname ] || byname=$($BB find /dev/block/platform -type d -name by-name 2>/dev/null | $BB head -n1 | $BB cut -d/ -f4-);
-  [ -d /dev/block/mapper ] && byname=mapper;
-  [ -e /dev/block/$byname/system ] || slot=$(find_slot);
   case $ANDROID_ROOT in
     /system_root) setup_mountpoint /system;;
     /system)
       if ! is_mounted /system && ! is_mounted /system_root; then
         setup_mountpoint /system_root;
-        $BB mount -o ro -t auto /system_root;
+         mount -o ro -t auto /system_root;
       elif [ -f /system/system/build.prop ]; then
         setup_mountpoint /system_root;
-        $BB mount --move /system /system_root;
+         mount --move /system /system_root;
       fi;
       if [ $? != 0 ]; then
-        ($BB umount /system;
-        $BB umount -l /system) 2>/dev/null;
-        $BB mount -o ro -t auto /dev/block/$byname/system$slot /system_root;
+        ( umount /system;
+         umount -l /system) 2>/dev/null;
+        if [ -d /dev/block/mapper ]; then
+          [ -e /dev/block/mapper/system ] || local slot=$(find_slot);
+           mount -o ro -t auto /dev/block/mapper/vendor$slot /vendor;
+           mount -o ro -t auto /dev/block/mapper/product$slot /product 2>/dev/null;
+           mount -o ro -t auto /dev/block/mapper/system$slot /system_root;
+           mount -o ro -t auto /dev/block/mapper/system_ext$slot /system_ext;
+        else
+          [ -e /dev/block/bootdevice/by-name/system ] || local slot=$(find_slot);
+          ( mount -o ro -t auto /dev/block/bootdevice/by-name/vendor$slot /vendor;
+           mount -o ro -t auto /dev/block/bootdevice/by-name/product$slot /product;
+           mount -o ro -t auto /dev/block/bootdevice/by-name/persist$slot /persist) 2>/dev/null;
+           mount -o ro -t auto /dev/block/bootdevice/by-name/system$slot /system_root;
+        fi;
       fi;
     ;;
   esac;
-  [ -f /system_root/system/build.prop ] && system=/system;
-  for mount in /vendor /product /system_ext; do
-    if ! is_mounted $mount && [ -L /system$mount -o -L /system_root$system$mount ]; then
-      setup_mountpoint $mount;
-      $BB mount -o ro -t auto /dev/block/$byname$mount$slot $mount;
-    fi;
-  done;
+  if [ -d /dev/block/mapper ]; then
+    for block in system vendor product system_ext; do
+      for slot in "" _a _b; do
+        blockdev --setrw /dev/block/mapper/$block$slot 2>/dev/null
+      done
+    done
+  fi
   if is_mounted /system_root; then
     mount_apex;
-    $BB mount -o bind /system_root$system /system;
-  fi;
-  if ! is_mounted /persist && [ -e /dev/block/bootdevice/by-name/persist ]; then
-    setup_mountpoint /persist;
-    $BB mount -o ro -t auto /dev/block/bootdevice/by-name/persist /persist;
+    #if [ -f /system_root/build.prop ]; then
+       #mount -o bind /system_root /system;
+    #else
+       #mount -o bind /system_root/system /system;
+    #fi;
   fi;
 }
 umount_all() {
   local mount;
   (if [ ! -d /postinstall/tmp ]; then
-    $BB umount /system;
-    $BB umount -l /system;
+    umount /system;
+    umount -l /system;
   fi) 2>/dev/null;
   umount_apex;
   (if [ ! -d /postinstall/tmp ]; then
-    $BB umount /system_root;
-    $BB umount -l /system_root;
+    umount /system_root;
+    umount -l /system_root;
   fi;
   umount /vendor; # busybox umount /vendor breaks recovery on some hacky devices
   umount -l /vendor;
   for mount in /mnt/system /mnt/vendor /product /mnt/product /system_ext /mnt/system_ext /persist; do
-    $BB umount $mount;
-    $BB umount -l $mount;
+    umount $mount;
+    umount -l $mount;
   done;
   if [ "$UMOUNT_DATA" ]; then
-    $BB umount /data;
-    $BB umount -l /data;
+    umount /data;
+    umount -l /data;
   fi;
   if [ "$UMOUNT_CACHE" ]; then
-    $BB umount /cache;
-    $BB umount -l /cache;
+    umount /cache;
+    umount -l /cache;
   fi) 2>/dev/null;
 }
 setup_env() {
   $BOOTMODE && return 1;
-  $BB mount -o bind /dev/urandom /dev/random;
+  mount -o bind /dev/urandom /dev/random;
   if [ -L /etc ]; then
     setup_mountpoint /etc;
-    $BB cp -af /etc_link/* /etc;
-    $BB sed -i 's; / ; /system_root ;' /etc/fstab;
+    cp -af /etc_link/* /etc;
+    sed -i 's; / ; /system_root ;' /etc/fstab;
   fi;
   umount_all;
   mount_all;
@@ -346,7 +354,7 @@ setup_env() {
     }
   elif [ ! "$(getprop ro.build.type 2>/dev/null)" ]; then
     getprop() {
-      ($(which getprop) | $BB grep "$1" | $BB cut -d[ -f3 | $BB cut -d] -f1) 2>/dev/null;
+      ($(which getprop) | grep "$1" | cut -d[ -f3 | cut -d] -f1) 2>/dev/null;
     }
   fi;
 }
@@ -359,24 +367,25 @@ restore_env() {
   [ "$OLD_LD_CFG" ] && export LD_CONFIG_FILE=$OLD_LD_CFG;
   unset OLD_LD_PATH OLD_LD_PRE OLD_LD_CFG;
   umount_all;
-  [ -L /etc_link ] && $BB rm -rf /etc/*;
+  [ -L /etc_link ] && rm -rf /etc/*;
   (for dir in /etc /apex /system_root /system /vendor /product /system_ext /persist; do
     if [ -L "${dir}_link" ]; then
       rmdir $dir;
-      $BB mv -f ${dir}_link $dir;
+      mv -f ${dir}_link $dir;
     fi;
   done;
-  $BB umount -l /dev/random) 2>/dev/null;
+  umount -l /dev/random) 2>/dev/null;
 }
 
 if $BOOTMODE; then
 	mount -o rw,remount -t auto / || mount -o rw,remount / 2>/dev/null;
 else
 	setup_env
-	for W78 in /system /product /system_ext /system_root /vendor; do
-		mount -o rw,remount -t auto $W78 || mount -o rw,remount $W78
+	for W78 in /system /product /system_ext /system_root /vendor /; do
+		mount -o rw,remount -t auto $W78 2>/dev/null;
 	done
 fi
+
 #########################################
 #    Kopi Script
 ########################################
@@ -399,10 +408,10 @@ system=/system
 fi
 
 #Extract
-kopi=/tmp/kopi
+kopi=/dev/tmp/kopi
 MODPATH=$kopi
-TMPDIR=/tmp
-cdir $kopi || print "failed create $kopi dir"
+TMPDIR=/dev/tmp
+cdir $kopi || abort "! Failed create $kopi dir"
 cd $kopi
 print "- Extracting ZIP File"
 unzip -o "$ZIPFILE" >&2
